spring:
  #  h2:
  #    console:
  #      enabled: true
  #      path: /h2-console
  datasource:
    #    driver-class-name: org.h2.Driver
    #    url: jdbc:h2:mem:test
    #    username: sa
    #    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lecture
    username: root
    password: pcs8437!
  jpa:
    hibernate:
      ddl-auto: create
    #    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true